language: python
env:
  - DJANGO_VERSION=1.5
python:
  - "2.7"
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  - pip install . --use-mirrors
  - pip install pep8 pyflakes --use-mirrors
before_script:
  - "cp sfpirgapp/local_settings.py.template sfpirgapp/local_settings.py"
script:
  - ./sfpirgapp/manage.py test
notifications:
  email:
    - vlad@bjola.ca
    - hderaps@vcn.bc.ca

